version: '3'

services:
  tesi_db:
    image: mariadb
    container_name: tesi_db
    restart: unless-stopped
    ports:
      - 3306:3306
    volumes:
      - db_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=ciao12345
      - MYSQL_DATABASE=anomaly_detection

volumes:
  db_data:
